### ISSUE TITLE
Handshake failure

### ISSUE THREAD

**Issue by foxyreign** [dgorissen/coursera-dl#177]
foxyreign@Foxy-Ubuntu:~/Dropbox/Coursera$ coursera-dl -u adrian@foxyreign.com textretrieval-001
Coursera-dl v3.1.1 (html.parser)
Password: 
Logging in as 'adrian@foxyreign.com'...
Traceback (most recent call last):
  File "/usr/local/bin/coursera-dl", line 9, in <module>
    load_entry_point('coursera-dl==3.1.1', 'console_scripts', 'coursera-dl')()
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 648, in main
    d.login(args.course_names[0])
  File "/usr/local/lib/python2.7/dist-packages/courseradownloader/courseradownloader.py", line 133, in login
    res = opener.open(req)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 442, in error
    result = self._call_chain(_args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(_args)
  File "/usr/lib/python2.7/urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

**Comment by hammett** [comment]
Getting this too. Was working up to a few days ago.. wondering what happened.

**Comment by ICodeEverything** [comment]
Coursera patched their ssl for POODLE. If you upgrade to python 2.7.9 it will fix this issue.

**Comment by hammett** [comment]
Thanks!

On Sat, Apr 4, 2015 at 11:18 AM, ICodeEverything notifications@github.com
wrote:

> Coursera patched their ssl for POODLE. If you upgrade to python 2.7.9 it
> will fix this issue.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dgorissen/coursera-dl/issues/177#issuecomment-89633168
> .

## 

Cheers,
hammett
http://www.d-collab.com/
http://www.hammettblog.com/

**Comment by foxyreign** [comment]
I upgraded to Python 2.7.9 and checked for most updated coursera-dl but I still get the handshake failure

![screenshot from 2015-04-05 19 13 56](https://cloud.githubusercontent.com/assets/6061469/6996689/0e6a38ec-dbc8-11e4-81a2-2441699a69ca.png)

**Comment by solocshaw** [comment]
![screen shot 2015-04-08 at 2 23 10 pm](https://cloud.githubusercontent.com/assets/4841820/7053469/fa9bffdc-ddfa-11e4-946b-8509eaac9eb2.png)
Yep. Handshake failure even after updating to 2.7.9. I'm on OSX 10.10.

**Comment by nitingupta180** [comment]
Yes. Same error is coming for me. I am on OSx Yosemite 10.10.3 and python version 2.7.6.

However I am able to download some courses (Machine Learning) but for most of the courses it is throwing above error.

Can anybody help?
